project:
  type: website
  output-dir: docs

website:
  title: Retroweb
  page-navigation: true
  repo-url: https://github.com/retostauffer/retroweb-template
  repo-branch: main
  repo-actions: issue
  navbar:
    pinned: false
    logo: assets/logo-retroweb-black.svg
    left:
      - href: index.qmd
        text: Home
      - text: Features
        menu:
          - href: webheader.qmd
          - href: blockcarousel.qmd
          - href: jquery.qmd
      - href: blog.qmd
        text: Blog
      - href: titleblocks.qmd
        text: To fix

    right:
      - href: about.qmd
        text: About
  page-footer:
    left:
      - text: About the site
      - text: About
        href: about.qmd
      - text: Blog
        href: blog.qmd
    center:
      - text: External
      - text: google
        href: https://www.google.com
    right:
      - text: Social
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/

resources:
  - assets
  - header-images

format:
  retroweb-html:
    date: 2022-08-17

twitter-card:
  - title: Retroweb - Quarto Website Theme
  - description: Template for Quarto-based website with the Retroweb theme!
  - image: assets/logo-retroweb.svg
  - image-alt: "Retroweb logo image"
  - card-style: summary
  - creator: "@retostauffer"
  - site: https://github.com/retostauffer/retroweb-template

open-graph:
  - title: Retroweb - Quarto Website Theme
  - description: Template for Quarto-based website with the Retroweb theme!
  - image: assets/logo-retroweb.svg
  - locale: en_US


