project:
  type: website
  output-dir: docs

website:
  title: Rotorweb
  page-navigation: true
  repo-url: https://github.com/retostauffer/rotorweb-template
  repo-branch: main
  repo-actions: issue
  navbar:
    pinned: false
    logo: assets/logo-rotorweb-black.svg
    left:
      - href: index.qmd
        text: Home
      - text: Features
        menu:
          - href: webheader.qmd
          - href: titleblocks.qmd
          - href: blockcarousel.qmd
          - href: jquery.qmd
      - href: blog.qmd
        text: Blog

    right:
      - href: about.qmd
        text: About
  page-footer:
    left:
      - text: About the site
      - text: About
        href: about.qmd
      - text: Blog
        href: blog.qmd
    center:
      - text: External
      - text: google
        href: https://www.google.com
    right:
      - text: Social
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/

resources:
  - assets
  - header-images

format:
  rotorweb-html:
    date: 2022-08-17

twitter-card:
  - title: Rotorweb - Quarto Website Theme
  - description: Template for Quarto-based website with the Rotorweb theme!
  - image: assets/logo-rotorweb.svg
  - image-alt: "Rotorweb logo image"
  - card-style: summary
  - creator: "@retostauffer"
  - site: https://github.com/retostauffer/rotorweb-template

open-graph:
  - title: Rotorweb - Quarto Website Theme
  - description: Template for Quarto-based website with the Rotorweb theme!
  - image: assets/logo-rotorweb.svg
  - locale: en_US


